name: Install Pref

on: workflow_dispatch

jobs:
  other-1:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: npm install
    - run: npm run test
