name: Main

on:
  workflow_dispatch:
    inputs:
      workspace_id:
        description: 'Noodl workspace id'
        default: 06vxgu
        required: true
        type: string
      project_id:
        description: 'Noodl project id'
        default: a95582a8-944d-445b-8f94-76bff5bc3fc6
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          # - os: macos-latest
          # - os: windows-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Setup Noodl CLI
    #   uses: noodlapp/actions-setup-cli@latest

    - name: Setup node env 🏗
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - run: sh "${GITHUB_WORKSPACE}/.github/build.sh"
      env:
        NOODL_PROJECT_ID: ${{ inputs.project_id }}
        NOODL_USERNAME: ${{ secrets.NOODL_USERNAME }}
        NOODL_PASSWORD: ${{ secrets.NOODL_PASSWORD }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: noodl-app-build
        path: ./noodl-app-build.zip
