name: Main

on:
  workflow_dispatch:
    inputs:
      workspace_id:
        description: 'Noodl workspace id'
        default: 06vxgu
        required: true
        type: string
      project_id:
        description: 'Noodl project id'
        default: a95582a8-944d-445b-8f94-76bff5bc3fc6
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: darwin-latest
          - os: win32-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Setup Noodl CLI
    #   uses: noodlapp/actions-setup-cli@latest

    - name: Setup node env 🏗
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - run: npm install -g @noodl/noodl-cli@2.6.9-beta.220725923019

    - run: git --version

    #- run: |
    #  node --version
    #  node -e 'child_process.spawnSync("npm", ["--version"], { stdio: "inherit" });'
    #  node -e 'child_process.spawnSync("git", ["--version"], { stdio: "inherit" });'
        
    - name: Clone Noodl project
      run: noodl-cli project clone "${{ inputs.project_id }}" "./noodl-app"
      env:
        NOODL_USERNAME: ${{ secrets.NOODL_USERNAME }}
        NOODL_PASSWORD: ${{ secrets.NOODL_PASSWORD }}
        
    - name: Clone Noodl project with shell
      run: noodl-cli project clone "${{ inputs.project_id }}" "./noodl-app"
      env:
        NOODL_USERNAME: ${{ secrets.NOODL_USERNAME }}
        NOODL_PASSWORD: ${{ secrets.NOODL_PASSWORD }}
        NOODL_SHELL: /usr/bin/bash
        
    - name: Build Noodl app
      run: noodl-cli build ./noodl-app --outFile ./noodl-app-build.zip
      env:
        NOODL_USERNAME: ${{ secrets.NOODL_USERNAME }}
        NOODL_PASSWORD: ${{ secrets.NOODL_PASSWORD }}
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: noodl-app-build
        path: ./noodl-app-build.zip
