name: Main

on:
  workflow_dispatch:
    inputs:
      workspace_id:
        description: 'Noodl workspace id'
        required: true
        type: string
      project_id:
        description: 'Noodl project id'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Noodl CLI
      uses: noodlapp/actions-setup-cli@latest

    - name: Clone Noodl project
      run: |
        noodl-cli project clone \
          --workspace-id ${{ inputs.workspace_id }} \
          --project-id ${{ inputs.project_id }} \
          --path ./noodl-app
      env:
        NOODL_USERNAME: ${{ secrets.NOODL_USERNAME }}
        NOODL_PASSWORD: ${{ secrets.NOODL_USERNAME }}
        
    - name: Build Noodl app
      run: noodl-cli build --projectDir ./noodl-app --outFile ./noodl-app-build.zip
      env:
        NOODL_USERNAME: ${{ secrets.NOODL_USERNAME }}
        NOODL_PASSWORD: ${{ secrets.NOODL_USERNAME }}
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: noodl-app-build
        path: ./noodl-app-build.zip
