name: Main

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Test.'
        default: 'Hello'
        required: false
        type: string
  release:
    types: [published]

jobs:
  main:
    uses: erictuvesson/github-actions-test/.github/workflows/other-2.yml@main
    with:
      text: "Hello from Main #2"

  other-3:
    uses: erictuvesson/github-actions-test/.github/workflows/other-1.yml@main
    needs: [main]
    with:
      text: "Hello from Main #1"
