name: Main

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: ./.github/workflows/other-1.yml
      with:
        text: "Hello from Main #1"

    - uses: ./.github/workflows/other-2.yml
      with:
        text: "Hello from Main #2"
