name: Main

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: ./.github/workflows/other-3
      with:
        text: "Hello from Main #3"

  other-3:
    uses: erictuvesson/github-actions-test/.github/workflows/other-1.yml@main
    with:
      text: "Hello from Main #1"
