name: Main

on:
  workflow_dispatch:
    inputs:
      workspace_id:
        description: 'Noodl workspace id'
        default: 06vxgu
        required: true
        type: string
      project_id:
        description: 'Noodl project id'
        default: a95582a8-944d-445b-8f94-76bff5bc3fc6
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - name: Setup Noodl CLI
    #   uses: noodlapp/actions-setup-cli@latest

    - name: Setup node env 🏗
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - run: npm install -g @noodl/noodl-cli@2.6.9-beta.220725923017

    - name: Clone Noodl project
      run: noodl-cli project clone --workspace-id "${{ inputs.workspace_id }}" --project-id "${{ inputs.project_id }}" --path "./noodl-app"
      env:
        NOODL_USERNAME: ${{ secrets.NOODL_USERNAME }}
        NOODL_PASSWORD: ${{ secrets.NOODL_PASSWORD }}
        
    - name: Build Noodl app
      run: noodl-cli build --projectDir ./noodl-app --outFile ./noodl-app-build.zip
      env:
        NOODL_USERNAME: ${{ secrets.NOODL_USERNAME }}
        NOODL_PASSWORD: ${{ secrets.NOODL_PASSWORD }}
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: noodl-app-build
        path: ./noodl-app-build.zip
