name: Other 2

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Test.'
        default: 'Hello'
        required: false
        type: string
  workflow_call:
    inputs:
      text:
        description: 'Test.'
        default: 'Hello'
        required: false
        type: string

jobs:
  other-1:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Hello World
      run: echo "The input text is ${{ inputs.text }}"
